PRODUCTS = {
    # ── D.L.T.A. Edition 150mg ────────────────────────────────
    "dlta_1": {
        "id": "dlta_1",
        "category": "snus",
        "name": "D.L.T.A. Apricot Strawberry Edition",
        "description": "Вкус: Абрикос и личи\n20 порций · 150mg никотина",
        "price": 200,
        "photo": "https://nico-kz1.com/wp-content/uploads/2025/10/NICOKAZ-SNUS-DLTA-apricot.jpg",
    },
    "dlta_2": {
        "id": "dlta_2",
        "category": "snus",
        "name": "D.L.T.A. Berry's Asai Edition",
        "description": "Вкус: Red Bull и ягоды асаи\n20 порций · 150mg никотина",
        "price": 200,
        "photo": "https://nico-kz1.com/wp-content/uploads/2025/10/NICOKAZ-SNUS-DLTA-purple.jpg",
    },
    "dlta_3": {
        "id": "dlta_3",
        "category": "snus",
        "name": "D.L.T.A. Blueberry Vanilla Eucalyptus Edition",
        "description": "Вкус: Черника, ежевика и жимолость\n20 порций · 150mg никотина",
        "price": 200,
        "photo": "https://nico-kz1.com/wp-content/uploads/2025/10/NICOKAZ-SNUS-DLTA-winter.jpg",
    },
    "dlta_4": {
        "id": "dlta_4",
        "category": "snus",
        "name": "D.L.T.A. Candy Blueberry Lemon",
        "description": "Вкус: Леденец черника лимон\n20 порций · 150mg никотина",
        "price": 200,
        "photo": "https://nico-kz1.com/wp-content/uploads/2025/10/NICOKAZ-SNUS-DLTA-winter.jpg",
    },
    "dlta_5": {
        "id": "dlta_5",
        "category": "snus",
        "name": "D.L.T.A. Forest Berry Edition",
        "description": "Вкус: Лесные ягоды\n20 порций · 150mg никотина",
        "price": 200,
        "photo": "https://nico-kz1.com/wp-content/uploads/2025/10/NICOKAZ-SNUS-DLTA-pink.jpg",
    },
    "dlta_6": {
        "id": "dlta_6",
        "category": "snus",
        "name": "D.L.T.A. Kaktus Edition",
        "description": "Вкус: Киви и яблоко\n20 порций · 150mg никотина",
        "price": 200,
        "photo": "https://nico-kz1.com/wp-content/uploads/2025/10/NICOKAZ-SNUS-DLTA-green-2.jpg",
    },
    "dlta_7": {
        "id": "dlta_7",
        "category": "snus",
        "name": "D.L.T.A. Kiwi Strawberry",
        "description": "Вкус: Киви клубника\n20 порций · 150mg никотина",
        "price": 200,
        "photo": "https://nico-kz1.com/wp-content/uploads/2025/10/NICOKAZ-SNUS-DLTA-KIWISTRAWBERRY.jpg",
    },
    "dlta_8": {
        "id": "dlta_8",
        "category": "snus",
        "name": "D.L.T.A. Kiwi-Apple Edition",
        "description": "Вкус: Red Bull и арбуз\n20 порций · 150mg никотина",
        "price": 200,
        "photo": "https://nico-kz1.com/wp-content/uploads/2025/10/NICOKAZ-SNUS-DLTA-summer.jpg",
    },
    "dlta_9": {
        "id": "dlta_9",
        "category": "snus",
        "name": "D.L.T.A. Lime Mint",
        "description": "Вкус: Лайм мята\n20 порций · 150mg никотина",
        "price": 200,
        "photo": "https://nico-kz1.com/wp-content/uploads/2025/10/NICOKAZ-SNUS-DLTA-LIMEMINT.jpg",
    },
    "dlta_10": {
        "id": "dlta_10",
        "category": "snus",
        "name": "D.L.T.A. Monster Killer Brew",
        "description": "Вкус: Кофе Loca Moca\n20 порций · 150mg никотина",
        "price": 200,
        "photo": "https://nico-kz1.com/wp-content/uploads/2025/10/NICOKAZ-SNUS-DLTA-winter.jpg",
    },
    "dlta_11": {
        "id": "dlta_11",
        "category": "snus",
        "name": "D.L.T.A. Orange Edition",
        "description": "Вкус: Апельсин\n20 порций · 150mg никотина",
        "price": 200,
        "photo": "https://nico-kz1.com/wp-content/uploads/2025/10/NICOKAZ-SNUS-DLTA-orange.jpg",
    },
    "dlta_12": {
        "id": "dlta_12",
        "category": "snus",
        "name": "D.L.T.A. Peach Edition",
        "description": "Вкус: Персик\n20 порций · 150mg никотина",
        "price": 200,
        "photo": "https://nico-kz1.com/wp-content/uploads/2025/10/NICOKAZ-SNUS-DLTA-peach.jpg",
    },
    "dlta_13": {
        "id": "dlta_13",
        "category": "snus",
        "name": "D.L.T.A. Peach Mango Watermelon",
        "description": "Вкус: Персик манго арбуз\n20 порций · 150mg никотина",
        "price": 200,
        "photo": "https://nico-kz1.com/wp-content/uploads/2025/10/NICOKAZ-SNUS-DLTA-PEACH-MANGO.jpg",
    },
    "dlta_14": {
        "id": "dlta_14",
        "category": "snus",
        "name": "D.L.T.A. Peach Yogurt",
        "description": "Вкус: Персик йогурт\n20 порций · 150mg никотина",
        "price": 200,
        "photo": "https://nico-kz1.com/wp-content/uploads/2025/10/NICOKAZ-SNUS-DLTA-PEACHYOHGURT.jpg",
    },
    "dlta_15": {
        "id": "dlta_15",
        "category": "snus",
        "name": "D.L.T.A. Pomegranate Lime",
        "description": "Вкус: Гранат лайм\n20 порций · 150mg никотина",
        "price": 200,
        "photo": "https://nico-kz1.com/wp-content/uploads/2025/10/NICOKAZ-SNUS-DLTA-POMEGRANATE-lIME.jpg",
    },
    "dlta_16": {
        "id": "dlta_16",
        "category": "snus",
        "name": "D.L.T.A. Raspberry Blackcurrant",
        "description": "Вкус: Малина черная смородина\n20 порций · 150mg никотина",
        "price": 200,
        "photo": "https://nico-kz1.com/wp-content/uploads/2025/10/NICOKAZ-SNUS-DLTA-RASPBERRY-BLACKCURRANT.jpg",
    },
    "dlta_17": {
        "id": "dlta_17",
        "category": "snus",
        "name": "D.L.T.A. Ice Cool Strong",
        "description": "Вкус: Мята\n20 порций · 155mg никотина",
        "price": 200,
        "photo": "https://nico-kz1.com/wp-content/uploads/2025/10/NICOKAZ-SNUS-DLTA-winter.jpg",
    },

    # ── D.L.T.A. Deluxe 100mg ─────────────────────────────────
    "dlta_d1": {
        "id": "dlta_d1",
        "category": "snus",
        "name": "D.L.T.A. Deluxe – Blackberry Grape Mint",
        "description": "Вкус: Ежевика виноград мята\n20 порций · 100mg никотина",
        "price": 200,
        "photo": "https://nico-kz1.com/wp-content/uploads/2025/01/dlta-deluxe-snus-kazakhstan-blackberry-grape-mint.png",
    },
    "dlta_d2": {
        "id": "dlta_d2",
        "category": "snus",
        "name": "D.L.T.A. Deluxe – Blueberry Jam",
        "description": "Вкус: Черника джем\n20 порций · 100mg никотина",
        "price": 200,
        "photo": "https://nico-kz1.com/wp-content/uploads/2025/01/dlta-deluxe-snus-kazakhstan-blueberry-jam.png",
    },
    "dlta_d3": {
        "id": "dlta_d3",
        "category": "snus",
        "name": "D.L.T.A. Deluxe – Cola Cherry",
        "description": "Вкус: Кола вишня\n20 порций · 100mg никотина",
        "price": 200,
        "photo": "https://nico-kz1.com/wp-content/uploads/2025/01/dlta-deluxe-snus-kazakhstan-cola-cherry.png",
    },
    "dlta_d4": {
        "id": "dlta_d4",
        "category": "snus",
        "name": "D.L.T.A. Del
